FROM eclipse-temurin:25-jdk-jammy AS build
WORKDIR /app
RUN apt-get update \
 && apt-get install -y maven \
 && rm -rf /var/lib/apt/lists/*

COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn -U clean package -DskipTests -Dspring-boot.repackage.skip=true

FROM eclipse-temurin:25-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
